version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - npm install -g yarn
      - yarn install
  build:
    commands:
      - yarn build:staging
  post_build:
    commands:
      - echo clear cloudfront cache
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRO_ID --paths "/*"
artifacts:
  base-directory: build
  files:
    - '**/*'

cache:
  paths:
    - /root/.npm/**/*
